// Generated by gencpp from file move/detect_state.msg
// DO NOT EDIT!


#ifndef MOVE_MESSAGE_DETECT_STATE_H
#define MOVE_MESSAGE_DETECT_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move
{
template <class ContainerAllocator>
struct detect_state_
{
  typedef detect_state_<ContainerAllocator> Type;

  detect_state_()
    : detect_state(false)  {
    }
  detect_state_(const ContainerAllocator& _alloc)
    : detect_state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _detect_state_type;
  _detect_state_type detect_state;





  typedef boost::shared_ptr< ::move::detect_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move::detect_state_<ContainerAllocator> const> ConstPtr;

}; // struct detect_state_

typedef ::move::detect_state_<std::allocator<void> > detect_state;

typedef boost::shared_ptr< ::move::detect_state > detect_statePtr;
typedef boost::shared_ptr< ::move::detect_state const> detect_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move::detect_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move::detect_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move::detect_state_<ContainerAllocator1> & lhs, const ::move::detect_state_<ContainerAllocator2> & rhs)
{
  return lhs.detect_state == rhs.detect_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move::detect_state_<ContainerAllocator1> & lhs, const ::move::detect_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move::detect_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move::detect_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::detect_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move::detect_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::detect_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move::detect_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move::detect_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb4ea15efeb62557142025112b232836";
  }

  static const char* value(const ::move::detect_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb4ea15efeb62557ULL;
  static const uint64_t static_value2 = 0x142025112b232836ULL;
};

template<class ContainerAllocator>
struct DataType< ::move::detect_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move/detect_state";
  }

  static const char* value(const ::move::detect_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move::detect_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool detect_state\n"
;
  }

  static const char* value(const ::move::detect_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move::detect_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.detect_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detect_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move::detect_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move::detect_state_<ContainerAllocator>& v)
  {
    s << indent << "detect_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detect_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_MESSAGE_DETECT_STATE_H
